"""added due_by column

Revision ID: 960e34b7e433
Revises: 40c93acb7117
Create Date: 2025-12-02 19:18:11.978675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960e34b7e433'
down_revision: Union[str, Sequence[str], None] = '40c93acb7117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_by', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'due_by')
    # ### end Alembic commands ###
